trigger:
  - master
  - develop
  - release/*
  - hotfix/*
  - feature/*

jobs:
  - job: setupenv
    steps:
      # set channel
      - bash: |
          echo "##vso[task.setvariable variable=channel]canary"
        condition: eq(variables['Build.SourceBranch'], 'refs/heads/develop')
      - bash: |
          echo "##vso[task.setvariable variable=channel]stable"
        condition: or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix/'))
      - bash: |
          echo "##vso[task.setvariable variable=channel]next"
        condition: startsWith(variables['Build.SourceBranch'], 'refs/heads/release/')
      # set branchtype
      - bash: |
          echo "##vso[task.setvariable variable=branchtype]indev"
        condition: or(startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/'), startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix/'))
      - bash: |
          echo "##vso[task.setvariable variable=branchtype]rel"
        condition: or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.SourceBranch'], 'refs/heads/develop'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/'))
      #output variables
      # - script: echo $(channel)
      #   name: echochannel
      # - script: echo $(branchtype)
      #   name: echobranchtype

  - template: scripts/build.yml
    parameters:
      os: "win"
      vmImage: "vs2017-win2016"
      channel: $(channel)

  - template: scripts/build.yml
    parameters:
      os: "lin"
      vmImage: "Ubuntu 16.04"
      channel: $(channel)

  - template: scripts/build.yml
    parameters:
      os: "mac"
      vmImage: "macOS-10.13"
      channel: $(channel)
# if branch release/*, merge changes into develop (or create pr if possible)
