jobs:
  - template: scripts/build.yml
    parameters:
      os: "win"
      vmImage: "vs2017-win2016"

  - template: scripts/build.yml
    parameters:
      os: "lin"
      vmImage: "Ubuntu 16.04"

  - template: scripts/build.yml
    parameters:
      os: "mac"
      vmImage: "macOS-10.13"
