parameters:
  os: "win"
  vmImage: "vs2017-win2016"
  channel: "canary"

jobs:
  - job: ${{format('{0}_Build',parameters.os)}}
    pool:
      vmImage: ${{parameters.vmImage}}
    dependsOn: setupenv

    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: "8.x"
        displayName: "Install Node.js"

      - script: npm install
        displayName: "npm install"

      - script: npm run prebuild
        displayName: "npm run prebuild"

      - script: npm run ${{format('build-{0}:{1}', parameters.os, parameters.channel)}}
        displayName: "npm run build"
