parameters:
  os: "win"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "8.x"
    displayName: "Install Node.js"

  - script: npm install
    displayName: "install npm packages"

  - script: npm run prebuild
    displayName: "prebuild"

  - script: npm run ${{format('build-{0}:', parameters.os)}}$(channel) -- -c.buildVersion=$(Build.BuildId)
    displayName: "build"

  - script: npm test
    displayName: "test"

  - bash: ls '$(Build.SourcesDirectory)'

  - task: CopyFiles@2
    inputs:
      sourceFolder: "$(Build.SourcesDirectory)/compiled"
      contents: "**"
      overWrite: true
      # artifactName: drop-$(parameters.os)
      targetFolder: "$(Build.ArtifactStagingDirectory)"
    displayName: "Copy all compiled files"

  - task: DeleteFiles@1
    inputs:
      contents: "*mac"
      sourceFolder: $(Build.ArtifactStagingDirectory)
    displayName: "Delete unpacked files"
  - task: DeleteFiles@1
    inputs:
      contents: "*unpacked"
      sourceFolder: $(Build.ArtifactStagingDirectory)
    displayName: "Delete unpacked files"
  - bash: |
      mkdir "windows"
      mkdir "mac"
      mkdir "linux"
      mkdir "linux-ia32"

      # move windows
      mv nsis-web/latest.yml $pwd
      mv nsis-web/* "windows/"
      rm nsis-web/

      # move mac
      mv *.dmg "mac/"
      mv *.dmg.blockmap "mac/"
      mv *mac.zip "mac/"

      # move linux
      mv *x86_64.AppImage "linux/"
      mv *i386.AppImage "linux-ia32/"

      # correct path mappings
      node -e "require('./scripts/setdistpaths.js').default('$(Build.ArtifactStagingDirectory)')"
      # node -e "require('./scripts/setdistpaths.js').default('$(pwd)')"
    displayName: "Move artifact files and correct mappings"

  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: "$(Build.ArtifactStagingDirectory)"
