# This is for CI builds of develop and develop PRs
# Ironically, this script does not actually run for the develop branch itself

trigger:
  branches:
    include:
      - feature/*
    exclude:
      - develop
      - master
      - hotfix/*
      - release/*
  paths:
    exclude:
      - .github/
      - /*.md
      - /*.graphml

pr:
  branches:
    include:
      - develop
      - feature/*
    exclude:
      - master
      - hotfix/*
      - release/*

variables:
  channel: "canary"

jobs:

  - job: win_build
    pool:
      vmImage: "vs2017-win2016"
    steps:
      - template: build.yml

  - job: lin_build
    pool:
      vmImage: "Ubuntu 16.04"
    steps:
      - template: build.yml

  - job: mac_build
    pool:
      vmImage: "macOS-10.13"
    steps:
      - template: build.yml
