trigger:
  branches:
    include:
      - master
      - hotfix/*
    exclude:
      - develop
      - feature/*
      - release/*
  paths:
    exclude:
      - .github/
      - /*.md
      - /*.graphml

pr:
  branches:
    include:
      - master
      - hotfix/*
    exclude:
      - develop
      - feature/*
      - release/*

variables:
  channel: "stable"

jobs:
  - job: setupenv
    pool:
      vmImage: "macOS-10.13"
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: "8.x"
        displayName: "Install Node.js"
      - bash: |
          echo "##vso[task.setvariable variable=branchtype]indev"
        condition: or(startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/'), startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix/'))
      - bash: |
          echo "##vso[task.setvariable variable=branchtype]rel"
        condition: or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.SourceBranch'], 'refs/heads/develop'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/'))
      - bash: |
          echo "##vso[task.setvariable variable=branchtype;isOutput=true]"$(branchtype)
        name: echobranchtype
      - checkout: self
        persistCredentials: true
      - script: npm install
        displayName: "install npm packages"
      - bash: node -p 'require("./scripts/getver.js").default()'
        displayName: "Show current version"
      - bash: | # on merge from hotfix, bump patch
          git config --global user.email "${gitemail}"
          git config --global user.name "${gitname}"
          echo commit is merge from hotfix
          git checkout master
          echo git status
          git status
          echo increment patch ver
          node -e "require('./scripts/bumpver.js').default({'channel':'stable','bump':'patch'})"
          echo add package
          git add "package.json"
          newver="$(node -p 'require("./scripts/getver.js").default()')"
          echo commit
          git commit -m "Bump patch ver to ${newver} ***NO_CI***"
          echo tag
          git tag "${newver}"
          echo git status
          git status
          echo git push
          git push --tags origin
          echo git status
          git status
        failOnStderr: true
        displayName: "Bump patch version"
        condition: and(or(and(startsWith(variables['Build.SourceVersionMessage'], 'Merge pull request'), contains(variables['Build.SourceVersionMessage'], 'from'), contains(variables['Build.SourceVersionMessage'], '/hotfix/')), and(startsWith(variables['Build.SourceVersionMessage'], 'Merge branch '), contains(variables['Build.SourceVersionMessage'], 'hotfix/'))), ne(variables['Build.Reason'], 'PullRequest')) # Approximately matches either "Merge pull request*from*/hotfix/*" or "Merge branch '/hotfix/*"
      - bash: | # on merge from release, remove channel info
          git config --global user.email "${gitemail}"
          git config --global user.name "${gitname}"
          echo commit is merge from release
          git checkout master
          echo git status
          git status
          echo increment patch ver
          node -e "require('./scripts/bumpver.js').default({'channel':'stable','bump':''})"
          echo add package
          git add "package.json"
          newver="$(node -p 'require("./scripts/getver.js").default()')"
          echo commit
          git commit -m "Switch channel info to stable ***NO_CI***"
          echo tag
          git tag "${newver}"
          echo git status
          git status
          echo git push
          git push --tags origin
          echo git status
          git status
        failOnStderr: true
        displayName: "Switch channel info to release"
        condition: and(or(and(startsWith(variables['Build.SourceVersionMessage'], 'Merge pull request'), contains(variables['Build.SourceVersionMessage'], 'from'), contains(variables['Build.SourceVersionMessage'], '/release/')), and(startsWith(variables['Build.SourceVersionMessage'], 'Merge branch '), contains(variables['Build.SourceVersionMessage'], 'release/'))), ne(variables['Build.Reason'], 'PullRequest')) # Approximately matches either "Merge pull request*from*/release/*" or "Merge branch '/release/*"

  # TODO if someone can do better conditions, then pls do

  - job: win_build
    pool:
      vmImage: "vs2017-win2016"
    dependsOn: setupenv
    steps:
      - template: build.yml
        parameters:
          os: "win"

  - job: lin_build
    pool:
      vmImage: "Ubuntu 16.04"
    dependsOn: setupenv
    steps:
      - template: build.yml
        parameters:
          os: "lin"

  - job: mac_build
    pool:
      vmImage: "macOS-10.13"
    dependsOn: setupenv
    steps:
      - template: build.yml
        parameters:
          os: "mac"
