# TODO: On release pipeline, update version info(?) and tag release

trigger:
  branches:
    include:
      - develop
      - feature/*
    exclude:
      - master
      - hotfix/*
      - release/*
  paths:
    exclude:
      - .github/
      - /*.md
      - /*.graphml

pr:
  branches:
    include:
      - develop
      - feature/*
    exclude:
      - master
      - hotfix/*
      - release/*

variables:
  channel: "canary"

jobs:
  - job: setupenv
    steps:
      - bash: | # Switch channel info if incorrect
          ./updpackagechannel.sh
        # failOnStderr: true
        displayName: "Switch channel info to $(channel)"

  - job: win_build
    pool:
      vmImage: "vs2017-win2016"
    dependsOn: setupenv
    steps:
      - template: build.yml
        parameters:
          os: "win"

  - job: lin_build
    pool:
      vmImage: "Ubuntu 16.04"
    dependsOn: setupenv
    steps:
      - template: build.yml
        parameters:
          os: "lin"

  - job: mac_build
    pool:
      vmImage: "macOS-10.13"
    dependsOn: setupenv
    steps:
      - template: build.yml
        parameters:
          os: "mac"
