# This is for CI builds of the develop branch only, which are to be possibly released as canary

trigger:
  branches:
    include:
      - develop
    exclude:
      - feature/*
      - master
      - hotfix/*
      - release/*
  paths:
    exclude:
      - .github/
      - /*.md
      - /*.graphml

pr: none

variables:
  channel: "canary"

jobs:

  - job: win_build
    pool:
      vmImage: "vs2017-win2016"
    steps:
      - template: build.yml

  - job: lin_build
    pool:
      vmImage: "Ubuntu 16.04"
    steps:
      - template: build.yml

  - job: mac_build
    pool:
      vmImage: "macOS-10.13"
    steps:
      - template: build.yml
