trigger:
  branches:
    include:
      - release/*
    exclude:
      - master
      - develop
      - feature/*
      - hotfix/*
  paths:
    exclude:
      - .github/
      - /*.md
      - /*.graphml

pr:
  branches:
    include:
      - release/*
    exclude:
      - master
      - develop
      - feature/*
      - hotfix/*

variables:
  channel: "next"

jobs:
  - job: setupenv
    steps:
      # - bash: |
      #     echo "##vso[task.setvariable variable=branchtype]indev"
      #   condition: or(startsWith(variables['Build.SourceBranch'], 'refs/heads/feature/'), startsWith(variables['Build.SourceBranch'], 'refs/heads/hotfix/'))

      # - bash: |
      #     echo "##vso[task.setvariable variable=branchtype]rel"
      #   condition: or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), eq(variables['Build.SourceBranch'], 'refs/heads/develop'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/'))

      # - bash: |
      #     echo "##vso[task.setvariable variable=branchtype;isOutput=true]"$(branchtype)
      #   name: echobranchtype

      - bash: | # Switch channel info if incorrect
          ./updpackagechannel.sh
        # failOnStderr: true
        displayName: "Switch channel info to $(channel)"

  - job: win_build
    pool:
      vmImage: "vs2017-win2016"
    dependsOn: setupenv
    steps:
      - template: build.yml
        parameters:
          os: "win"

  - job: lin_build
    pool:
      vmImage: "Ubuntu 16.04"
    dependsOn: setupenv
    steps:
      - template: build.yml
        parameters:
          os: "lin"

  - job: mac_build
    pool:
      vmImage: "macOS-10.13"
    dependsOn: setupenv
    steps:
      - template: build.yml
        parameters:
          os: "mac"
  # continuously merge to develop if test passes
  - job: release_merge
    pool:
      vmImage: "Ubuntu 16.04"
    dependsOn:
      - win_build
      - lin_build
      - mac_build
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/release/'))
    steps:
      - template: releasetodevelop.yml
# if branch release/*,  merge changes into develop (or create pr if possible)
