trigger:
  branches:
    include:
      - release/*
    exclude:
      - master
      - develop
      - feature/*
      - hotfix/*
  paths:
    exclude:
      - .github/
      - /*.md
      - /*.graphml

pr:
  branches:
    include:
      - release/*
    exclude:
      - master
      - develop
      - feature/*
      - hotfix/*

variables:
  channel: "next"

jobs:

  - job: win_build
    pool:
      vmImage: "vs2017-win2016"
    steps:
      - template: build.yml

  - job: lin_build
    pool:
      vmImage: "Ubuntu 16.04"
    steps:
      - template: build.yml

  - job: mac_build
    pool:
      vmImage: "macOS-10.13"
    steps:
      - template: build.yml
